name: Cypress Tests
on: 
  push:
    branches: 
      - main # Runs the workflow on pushes to the main branch
  pull_request: # Optionally run on pull requests
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1] # Run tests in 2 parallel containers

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0 # Specify Node.js version explicitly
          cache: 'npm' # Cache npm modules to improve build performance

      - name: Verify Node.js Version
        run: node -v # Check and confirm the Node.js version in the logs

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cypress:e2e:report
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Recording key for Cypress Cloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication, if required
